server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/foodie
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      minimum-idle: 1
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 30000

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      schema: public
